version: "3.9"

services:
  go_db:
    container_name: go_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: 1234
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TODO_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}